version: '3.7'
services:
  postgres_demo:
    image: postgres:12.2-alpine
    container_name: postgres_demo
    networks:
    - lab
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    privileged: true
  demo_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_service
    links:
      - postgres_demo
    networks:
    - lab
    ports:
    - 8080:8080
    environment:
      spring.datasource.url: jdbc:postgresql://postgres_demo:5432/demo
      spring.datasource.username: postgres
      spring.datasource.password: postgres
    privileged: true

networks:
  lab:
    name: lab
    driver: bridge
